// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaXjtxDIFF_eAlpfxzQ44OJyQ-2CgAUyA',
    appId: '1:54265541767:web:258a0a6f542cd70c15b422',
    messagingSenderId: '54265541767',
    projectId: 'familycir',
    authDomain: 'familycir.firebaseapp.com',
    storageBucket: 'familycir.firebasestorage.app',
    measurementId: 'G-S0YCY56ED7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUifKgiWlTjeYt1Dh5fufJR_4CfgN5fQ8',
    appId: '1:54265541767:android:c4b60123cd84056e15b422',
    messagingSenderId: '54265541767',
    projectId: 'familycir',
    storageBucket: 'familycir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFyacX3HCbhlXzmzU_7MgDHLAUB0Hpz7w',
    appId: '1:54265541767:ios:50fe60add2c6b8e315b422',
    messagingSenderId: '54265541767',
    projectId: 'familycir',
    storageBucket: 'familycir.firebasestorage.app',
    iosBundleId: 'com.familycircle.familyCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFyacX3HCbhlXzmzU_7MgDHLAUB0Hpz7w',
    appId: '1:54265541767:ios:afe3b8dc6c9557c715b422',
    messagingSenderId: '54265541767',
    projectId: 'familycir',
    storageBucket: 'familycir.firebasestorage.app',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaXjtxDIFF_eAlpfxzQ44OJyQ-2CgAUyA',
    appId: '1:54265541767:web:c6b1f632af8b76f415b422',
    messagingSenderId: '54265541767',
    projectId: 'familycir',
    authDomain: 'familycir.firebaseapp.com',
    storageBucket: 'familycir.firebasestorage.app',
    measurementId: 'G-J0KQY2B50Q',
  );
}
